import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header/Header";
import { ToastContainer } from "react-toastify";
import StoreProvider from "../components/storeProvider/StoreProviderCustom";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`antialiased`}
        >
          <div className='container-main'>
            <ToastContainer />
            <Header />
            {children}
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
